language: php
sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - EXECUTE_DEPLOYMENT=true
    - php: 7

before_install:
  - openssl aes-256-cbc -K $encrypted_5a55c0623410_key -iv $encrypted_5a55c0623410_iv
    -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
  - phpenv config-rm xdebug.ini
  - composer selfupdate

install:
  - composer install

script:
  - "./vendor/bin/phpunit tests"

after_success:
  - if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then composer install --no-dev ; fi
  - if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./bin/deploy.sh ; fi
